name: blast_caller_app
description: A Flutter application for Blast Caller System
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.63.0  # Updated to latest version
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  http: ^1.1.0  # For API requests
  flutter_secure_storage: ^8.0.0  # For securely storing auth tokens

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/